
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Roberts Erts
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registration = new javax.swing.JDialog();
        registrationPanel = new javax.swing.JPanel();
        registrationLabel1 = new javax.swing.JLabel();
        registrationLabel2 = new javax.swing.JLabel();
        registrationLabel3 = new javax.swing.JLabel();
        registrationLabel4 = new javax.swing.JLabel();
        registrationLabel5 = new javax.swing.JLabel();
        registrationLabel6 = new javax.swing.JLabel();
        registrationTextField1 = new javax.swing.JTextField();
        registrationTextField2 = new javax.swing.JTextField();
        registrationTextField3 = new javax.swing.JTextField();
        registrationTextField4 = new javax.swing.JTextField();
        registrationTextField5 = new javax.swing.JTextField();
        registrationRadioButton1 = new javax.swing.JRadioButton();
        registrationRadioButton2 = new javax.swing.JRadioButton();
        registrationLabel7 = new javax.swing.JLabel();
        registrationButton1 = new javax.swing.JButton();
        registrationButton2 = new javax.swing.JButton();
        registrationLabel8 = new javax.swing.JLabel();
        registrationBackground = new javax.swing.JLabel();
        registrationMenuBar = new javax.swing.JMenuBar();
        helpRegistrationMenu = new javax.swing.JMenu();
        registrationButtonGroup = new javax.swing.ButtonGroup();
        studentTest = new javax.swing.JDialog();
        studentTestPanel = new javax.swing.JPanel();
        stidentTestLabel = new javax.swing.JLabel();
        studentStartTestButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentTestBackground = new javax.swing.JLabel();
        studentTestMenuBar = new javax.swing.JMenuBar();
        helpStudentTestMenu = new javax.swing.JMenu();
        teacherTest = new javax.swing.JDialog();
        teacherTestPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        teacherTestBackground = new javax.swing.JLabel();
        teacherTestMenuBar = new javax.swing.JMenuBar();
        helpTeacherTestMenu = new javax.swing.JMenu();
        testQuestion = new javax.swing.JDialog();
        questionPanel2 = new javax.swing.JPanel();
        qLabel = new javax.swing.JLabel();
        question1 = new javax.swing.JButton();
        question2 = new javax.swing.JButton();
        question3 = new javax.swing.JButton();
        question4 = new javax.swing.JButton();
        question5 = new javax.swing.JButton();
        question6 = new javax.swing.JButton();
        question7 = new javax.swing.JButton();
        question8 = new javax.swing.JButton();
        question9 = new javax.swing.JButton();
        question10 = new javax.swing.JButton();
        question11 = new javax.swing.JButton();
        question12 = new javax.swing.JButton();
        question13 = new javax.swing.JButton();
        question14 = new javax.swing.JButton();
        question15 = new javax.swing.JButton();
        question16 = new javax.swing.JButton();
        question17 = new javax.swing.JButton();
        question18 = new javax.swing.JButton();
        question19 = new javax.swing.JButton();
        question20 = new javax.swing.JButton();
        questionEndButton = new javax.swing.JButton();
        questionPanel1 = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        questionRadioButton1 = new javax.swing.JRadioButton();
        questionRadioButton2 = new javax.swing.JRadioButton();
        questionRadioButton3 = new javax.swing.JRadioButton();
        nextQuestionButton = new javax.swing.JButton();
        testBackground = new javax.swing.JLabel();
        testMenuBar = new javax.swing.JMenuBar();
        helpTestMenu = new javax.swing.JMenu();
        questionButtonGroup = new javax.swing.ButtonGroup();
        result = new javax.swing.JDialog();
        resultPanel = new javax.swing.JPanel();
        resultLabel1 = new javax.swing.JLabel();
        resultLabel2 = new javax.swing.JLabel();
        percentageLabel1 = new javax.swing.JLabel();
        markLabel1 = new javax.swing.JLabel();
        resultLabel3 = new javax.swing.JLabel();
        percentageLabel2 = new javax.swing.JLabel();
        markLabel2 = new javax.swing.JLabel();
        seeAnswerButton = new javax.swing.JButton();
        resultEndButton = new javax.swing.JButton();
        resultBackground = new javax.swing.JLabel();
        resultMenuBar = new javax.swing.JMenuBar();
        helpResultMenu = new javax.swing.JMenu();
        mainPanel1 = new javax.swing.JPanel();
        mainPanel2 = new javax.swing.JPanel();
        mainLabel2_1 = new javax.swing.JLabel();
        mainLabel2_2 = new javax.swing.JLabel();
        mainLabel1_1 = new javax.swing.JLabel();
        mainLabel1_2 = new javax.swing.JLabel();
        mainLabel1_3 = new javax.swing.JLabel();
        mainTextField1 = new javax.swing.JTextField();
        mainTextField2 = new javax.swing.JTextField();
        mainButton1 = new javax.swing.JButton();
        mainLabel1_4 = new javax.swing.JLabel();
        mainButton2 = new javax.swing.JButton();
        mainBackground = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        helpMainMenu = new javax.swing.JMenu();

        registration.setTitle("Test");
        registration.setMaximumSize(new java.awt.Dimension(800, 630));
        registration.setMinimumSize(new java.awt.Dimension(800, 630));
        registration.setModal(true);
        registration.getContentPane().setLayout(null);

        registrationPanel.setBackground(new java.awt.Color(255, 255, 255));
        registrationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registrationLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrationLabel1.setText("Reģistrēšana ");

        registrationLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel2.setText("Vards : ");

        registrationLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel3.setText("Uzvards : ");

        registrationLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel4.setText("Lietotajvards : ");

        registrationLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel5.setText("Parole : ");

        registrationLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel6.setText("Parole (atkartoti) :");

        registrationTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registrationTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registrationTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registrationTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registrationTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        registrationButtonGroup.add(registrationRadioButton1);
        registrationRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationRadioButton1.setText("Skolēns");

        registrationButtonGroup.add(registrationRadioButton2);
        registrationRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationRadioButton2.setText("Skolotājs");

        registrationLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel7.setText("Es esmu :");

        registrationButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationButton1.setText("Reģistreties");
        registrationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButton1ActionPerformed(evt);
            }
        });

        registrationButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationButton2.setText("Ielogoties");
        registrationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButton2ActionPerformed(evt);
            }
        });

        registrationLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrationLabel8.setText("Jau ir konts? Tad ielogoties :");

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrationLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrationLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrationLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrationLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrationLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationButton1)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addComponent(registrationRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(registrationRadioButton2))
                    .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(registrationTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(registrationTextField1)
                        .addComponent(registrationTextField2)
                        .addComponent(registrationTextField3)
                        .addComponent(registrationTextField4)))
                .addGap(50, 50, 50))
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registrationLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrationButton2))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(registrationLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registrationLabel1)
                .addGap(28, 28, 28)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationLabel2))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationLabel3)
                    .addComponent(registrationTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationLabel4)
                    .addComponent(registrationTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationLabel5)
                    .addComponent(registrationTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationLabel6))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationRadioButton1)
                    .addComponent(registrationRadioButton2)
                    .addComponent(registrationLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrationButton1)
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationButton2)
                    .addComponent(registrationLabel8))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        registration.getContentPane().add(registrationPanel);
        registrationPanel.setBounds(122, 48, 556, 476);

        registrationBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        registration.getContentPane().add(registrationBackground);
        registrationBackground.setBounds(0, 0, 800, 600);

        helpRegistrationMenu.setText("Help");
        registrationMenuBar.add(helpRegistrationMenu);

        registration.setJMenuBar(registrationMenuBar);

        studentTest.setTitle("Test");
        studentTest.setMinimumSize(new java.awt.Dimension(800, 630));
        studentTest.setModal(true);
        studentTest.getContentPane().setLayout(null);

        studentTestPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentTestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        stidentTestLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        stidentTestLabel.setText("Tests “Nosaukums”");

        studentStartTestButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentStartTestButton.setText("Sakt testu");
        studentStartTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentStartTestButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Atteikties no konta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentTestPanelLayout = new javax.swing.GroupLayout(studentTestPanel);
        studentTestPanel.setLayout(studentTestPanelLayout);
        studentTestPanelLayout.setHorizontalGroup(
            studentTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTestPanelLayout.createSequentialGroup()
                .addGroup(studentTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentTestPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(stidentTestLabel))
                    .addGroup(studentTestPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(studentStartTestButton))
                    .addGroup(studentTestPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton2)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        studentTestPanelLayout.setVerticalGroup(
            studentTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTestPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(stidentTestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentStartTestButton)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        studentTest.getContentPane().add(studentTestPanel);
        studentTestPanel.setBounds(236, 200, 0, 0);

        studentTestBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        studentTest.getContentPane().add(studentTestBackground);
        studentTestBackground.setBounds(0, 0, 800, 600);

        helpStudentTestMenu.setText("Help");
        studentTestMenuBar.add(helpStudentTestMenu);

        studentTest.setJMenuBar(studentTestMenuBar);

        teacherTest.setTitle("Test");
        teacherTest.setMinimumSize(new java.awt.Dimension(800, 630));
        teacherTest.setModal(true);
        teacherTest.getContentPane().setLayout(null);

        teacherTestPanel.setBackground(new java.awt.Color(255, 255, 255));
        teacherTestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tests “Nosaukums”");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Sakt testu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Atteikties no konta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Testa statuss");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherTestPanelLayout = new javax.swing.GroupLayout(teacherTestPanel);
        teacherTestPanel.setLayout(teacherTestPanelLayout);
        teacherTestPanelLayout.setHorizontalGroup(
            teacherTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTestPanelLayout.createSequentialGroup()
                .addGroup(teacherTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherTestPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(teacherTestPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton3))
                    .addGroup(teacherTestPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1))
                    .addGroup(teacherTestPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton4)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        teacherTestPanelLayout.setVerticalGroup(
            teacherTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTestPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        teacherTest.getContentPane().add(teacherTestPanel);
        teacherTestPanel.setBounds(237, 185, 0, 0);

        teacherTestBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        teacherTest.getContentPane().add(teacherTestBackground);
        teacherTestBackground.setBounds(0, 0, 800, 600);

        helpTeacherTestMenu.setText("Help");
        teacherTestMenuBar.add(helpTeacherTestMenu);

        teacherTest.setJMenuBar(teacherTestMenuBar);

        testQuestion.setTitle("Test");
        testQuestion.setMinimumSize(new java.awt.Dimension(800, 630));
        testQuestion.setModal(true);
        testQuestion.getContentPane().setLayout(null);

        questionPanel2.setBackground(new java.awt.Color(255, 255, 255));
        questionPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        qLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qLabel.setText("Jautajumi :");

        question1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question1.setText("1");
        question1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1ActionPerformed(evt);
            }
        });

        question2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question2.setText("2");
        question2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question2ActionPerformed(evt);
            }
        });

        question3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question3.setText("3");
        question3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question3ActionPerformed(evt);
            }
        });

        question4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question4.setText("4");
        question4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question4ActionPerformed(evt);
            }
        });

        question5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question5.setText("5");
        question5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question5ActionPerformed(evt);
            }
        });

        question6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question6.setText("6");
        question6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question6ActionPerformed(evt);
            }
        });

        question7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question7.setText("7");
        question7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question7ActionPerformed(evt);
            }
        });

        question8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question8.setText("8");
        question8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question8ActionPerformed(evt);
            }
        });

        question9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question9.setText("9");
        question9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question9ActionPerformed(evt);
            }
        });

        question10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question10.setText("10");
        question10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question10ActionPerformed(evt);
            }
        });

        question11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question11.setText("11");
        question11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question11ActionPerformed(evt);
            }
        });

        question12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question12.setText("12");
        question12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question12ActionPerformed(evt);
            }
        });

        question13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question13.setText("13");
        question13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question13ActionPerformed(evt);
            }
        });

        question14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question14.setText("14");
        question14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question14ActionPerformed(evt);
            }
        });

        question15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question15.setText("15");
        question15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question15ActionPerformed(evt);
            }
        });

        question16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question16.setText("16");
        question16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question16ActionPerformed(evt);
            }
        });

        question17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question17.setText("17");
        question17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question17ActionPerformed(evt);
            }
        });

        question18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question18.setText("18");
        question18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question18ActionPerformed(evt);
            }
        });

        question19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question19.setText("19");
        question19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question19ActionPerformed(evt);
            }
        });

        question20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        question20.setText("20");
        question20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question20ActionPerformed(evt);
            }
        });

        questionEndButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questionEndButton.setText("Pabeigt darbu");
        questionEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionEndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionPanel2Layout = new javax.swing.GroupLayout(questionPanel2);
        questionPanel2.setLayout(questionPanel2Layout);
        questionPanel2Layout.setHorizontalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel2Layout.createSequentialGroup()
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanel2Layout.createSequentialGroup()
                        .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(questionPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(questionPanel2Layout.createSequentialGroup()
                                        .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(question19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(question16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(questionPanel2Layout.createSequentialGroup()
                                        .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(question9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(question8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(question10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(questionPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(qLabel))
                            .addGroup(questionPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(questionPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(questionPanel2Layout.createSequentialGroup()
                                        .addComponent(question5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(question6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(questionPanel2Layout.createSequentialGroup()
                                        .addComponent(question3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(question4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(questionEndButton)))
                .addContainerGap())
        );
        questionPanel2Layout.setVerticalGroup(
            questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(qLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1)
                    .addComponent(question2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question3)
                    .addComponent(question4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question6)
                    .addComponent(question5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question7)
                    .addComponent(question8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question10)
                    .addComponent(question9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question11)
                    .addComponent(question12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question14)
                    .addComponent(question13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question15)
                    .addComponent(question16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question18)
                    .addComponent(question17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question19)
                    .addComponent(question20))
                .addGap(18, 18, 18)
                .addComponent(questionEndButton)
                .addGap(30, 30, 30))
        );

        testQuestion.getContentPane().add(questionPanel2);
        questionPanel2.setBounds(610, 20, 0, 0);

        questionPanel1.setBackground(new java.awt.Color(255, 255, 255));
        questionPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        questionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        questionLabel.setText("1. Jautajums “Jautajuma teksts”");

        questionButtonGroup.add(questionRadioButton1);
        questionRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questionRadioButton1.setText("1. atbilde");

        questionButtonGroup.add(questionRadioButton2);
        questionRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questionRadioButton2.setText("2. atbilde");

        questionButtonGroup.add(questionRadioButton3);
        questionRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questionRadioButton3.setText("3. atbilde");

        nextQuestionButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nextQuestionButton.setText("Talak");
        nextQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionPanel1Layout = new javax.swing.GroupLayout(questionPanel1);
        questionPanel1.setLayout(questionPanel1Layout);
        questionPanel1Layout.setHorizontalGroup(
            questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel1Layout.createSequentialGroup()
                .addGroup(questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionRadioButton3)
                            .addComponent(questionRadioButton1)
                            .addComponent(questionLabel)
                            .addComponent(questionRadioButton2)))
                    .addGroup(questionPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(nextQuestionButton)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        questionPanel1Layout.setVerticalGroup(
            questionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(questionLabel)
                .addGap(50, 50, 50)
                .addComponent(questionRadioButton1)
                .addGap(30, 30, 30)
                .addComponent(questionRadioButton2)
                .addGap(30, 30, 30)
                .addComponent(questionRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(nextQuestionButton)
                .addGap(30, 30, 30))
        );

        testQuestion.getContentPane().add(questionPanel1);
        questionPanel1.setBounds(25, 120, 0, 0);

        testBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        testQuestion.getContentPane().add(testBackground);
        testBackground.setBounds(0, 0, 800, 600);

        helpTestMenu.setText("Help");
        testMenuBar.add(helpTestMenu);

        testQuestion.setJMenuBar(testMenuBar);

        result.setTitle("Test");
        result.setMinimumSize(new java.awt.Dimension(800, 630));
        result.setModal(true);
        result.getContentPane().setLayout(null);

        resultPanel.setBackground(new java.awt.Color(255, 255, 255));
        resultPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        resultLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultLabel1.setText("Rezultati");

        resultLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultLabel2.setText("Jusu rezultati");

        percentageLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        percentageLabel1.setText("Procenti: X%");

        markLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        markLabel1.setText("Atzime: A");

        resultLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultLabel3.setText("Vidēji rezultati");

        percentageLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        percentageLabel2.setText("Procenti: X%");

        markLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        markLabel2.setText("Atzime: A");

        seeAnswerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seeAnswerButton.setText("Apskatīt atbildes");
        seeAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAnswerButtonActionPerformed(evt);
            }
        });

        resultEndButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultEndButton.setText("Beigt");
        resultEndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultEndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resultLabel1)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultEndButton)
                .addContainerGap())
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel2)
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(markLabel1)
                                    .addComponent(percentageLabel1))))
                        .addGap(40, 40, 40)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel3)
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(markLabel2)
                                    .addComponent(percentageLabel2)))))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(seeAnswerButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(resultLabel1)
                .addGap(20, 20, 20)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel2)
                    .addComponent(resultLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageLabel1)
                    .addComponent(percentageLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markLabel1)
                    .addComponent(markLabel2))
                .addGap(18, 18, 18)
                .addComponent(seeAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultEndButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        result.getContentPane().add(resultPanel);
        resultPanel.setBounds(213, 146, 0, 0);

        resultBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        result.getContentPane().add(resultBackground);
        resultBackground.setBounds(0, 0, 800, 600);

        helpResultMenu.setText("Help");
        resultMenuBar.add(helpResultMenu);

        result.setJMenuBar(resultMenuBar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test");
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 630));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        mainPanel1.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainPanel2.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainLabel2_1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainLabel2_1.setText("Sveiki!");

        mainLabel2_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainLabel2_2.setText("Šajā lietotnē jūs varat pildīt testus");

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(mainLabel2_2))
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(mainLabel2_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mainLabel2_1)
                .addGap(18, 18, 18)
                .addComponent(mainLabel2_2)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainLabel1_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainLabel1_1.setText("Lietotāja pieslēgšanā");

        mainLabel1_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainLabel1_2.setText("Lietotājvārds : ");

        mainLabel1_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainLabel1_3.setText("Parole : ");

        mainTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainTextField1ActionPerformed(evt);
            }
        });

        mainTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mainButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainButton1.setText("Ielogoties");
        mainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButton1ActionPerformed(evt);
            }
        });

        mainLabel1_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainLabel1_4.setText("Konta nav? Izveidojiet to:");

        mainButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainButton2.setText("Reģistreties");
        mainButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(mainLabel1_1))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(mainLabel1_2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainLabel1_3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainButton1)
                            .addComponent(mainTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mainLabel1_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainButton2)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(mainPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainLabel1_1)
                .addGap(30, 30, 30)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel1_2)
                    .addComponent(mainTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel1_3)
                    .addComponent(mainTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mainButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel1_4)
                    .addComponent(mainButton2))
                .addGap(20, 20, 20))
        );

        getContentPane().add(mainPanel1);
        mainPanel1.setBounds(202, 30, 396, 503);

        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background2.png"))); // NOI18N
        getContentPane().add(mainBackground);
        mainBackground.setBounds(0, 0, 800, 580);

        helpMainMenu.setText("Help");
        mainMenuBar.add(helpMainMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTextField1ActionPerformed

    private void mainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButton1ActionPerformed
        try (BufferedReader reader = new BufferedReader(new FileReader("Lietotaji.txt"))) {
            
            } catch (IOException ex) {
                
            }

        setVisible(false);
        studentTest.setSize(800,650);
        studentTest.setLocationRelativeTo(null);
        studentTest.setVisible(true);
    }//GEN-LAST:event_mainButton1ActionPerformed

    private void mainButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButton2ActionPerformed
        setVisible(false);
        registration.setSize(800,650);
        registration.setLocationRelativeTo(null);
        registration.setVisible(true);
    }//GEN-LAST:event_mainButton2ActionPerformed

    private void registrationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButton1ActionPerformed
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Lietotaji.txt", true))) {
            if(registrationTextField4.getText().equals(registrationTextField5.getText()) && !"".equals(registrationTextField1.getText()) && !"".equals(registrationTextField2.getText()) && !"".equals(registrationTextField3.getText()) && !"".equals(registrationTextField4.getText()) && !"".equals(registrationTextField5.getText()))
            {
                writer.write("Vārds: " + registrationTextField1.getText());
                writer.newLine();
                writer.write("Uzvārds: " + registrationTextField2.getText());
                writer.newLine();
                writer.write("Lietotājvārds: " + registrationTextField3.getText());
                writer.newLine();
                writer.write("Parole: " + registrationTextField4.getText());
                writer.newLine();
                if(registrationRadioButton1.isSelected())
                {
                    writer.write("Lietotāja tips: " + "Skolēns");
                    writer.newLine();
                }
                if(registrationRadioButton2.isSelected())
                {
                    writer.write("Lietotāja tips: " + "Skolotājs");
                    writer.newLine();
                }
                writer.write("----------------------------");
                writer.newLine();
                JOptionPane.showMessageDialog(null, "Lietotājs saglabāts!", "Informācija", JOptionPane.INFORMATION_MESSAGE);
                
                registrationTextField1.setText("");
                registrationTextField2.setText("");
                registrationTextField3.setText("");
                registrationTextField4.setText("");
                registrationTextField5.setText("");
                registrationButtonGroup.clearSelection();
                
                registration.setVisible(false);
                setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Nepareizi ievadīti dati!", "Kļuda", JOptionPane.ERROR_MESSAGE);
                registrationTextField1.setText("");
                registrationTextField2.setText("");
                registrationTextField3.setText("");
                registrationTextField4.setText("");
                registrationTextField5.setText("");
                registrationButtonGroup.clearSelection();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Kļūda saglabājot datus!", "Kļuda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrationButton1ActionPerformed

    private void registrationButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButton2ActionPerformed
        registration.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_registrationButton2ActionPerformed

    private void question7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question7ActionPerformed

    private void question11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question11ActionPerformed

    private void studentStartTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentStartTestButtonActionPerformed
        setVisible(false);
        testQuestion.setSize(800,650);
        testQuestion.setLocationRelativeTo(null);
        testQuestion.setVisible(true);
    }//GEN-LAST:event_studentStartTestButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nextQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextQuestionButtonActionPerformed

    private void question1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question1ActionPerformed

    private void question2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question2ActionPerformed

    private void question3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question3ActionPerformed

    private void question4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question4ActionPerformed

    private void question5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question5ActionPerformed

    private void question6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question6ActionPerformed

    private void question8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question8ActionPerformed

    private void question9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question9ActionPerformed

    private void question10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question10ActionPerformed

    private void question12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question12ActionPerformed

    private void question13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question13ActionPerformed

    private void question14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question14ActionPerformed

    private void question15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question15ActionPerformed

    private void question16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question16ActionPerformed

    private void question17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question17ActionPerformed

    private void question18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question18ActionPerformed

    private void question19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question19ActionPerformed

    private void question20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question20ActionPerformed

    private void questionEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionEndButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionEndButtonActionPerformed

    private void seeAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAnswerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seeAnswerButtonActionPerformed

    private void resultEndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultEndButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultEndButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu helpMainMenu;
    private javax.swing.JMenu helpRegistrationMenu;
    private javax.swing.JMenu helpResultMenu;
    private javax.swing.JMenu helpStudentTestMenu;
    private javax.swing.JMenu helpTeacherTestMenu;
    private javax.swing.JMenu helpTestMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mainBackground;
    private javax.swing.JButton mainButton1;
    private javax.swing.JButton mainButton2;
    private javax.swing.JLabel mainLabel1_1;
    private javax.swing.JLabel mainLabel1_2;
    private javax.swing.JLabel mainLabel1_3;
    private javax.swing.JLabel mainLabel1_4;
    private javax.swing.JLabel mainLabel2_1;
    private javax.swing.JLabel mainLabel2_2;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JTextField mainTextField1;
    private javax.swing.JTextField mainTextField2;
    private javax.swing.JLabel markLabel1;
    private javax.swing.JLabel markLabel2;
    private javax.swing.JButton nextQuestionButton;
    private javax.swing.JLabel percentageLabel1;
    private javax.swing.JLabel percentageLabel2;
    private javax.swing.JLabel qLabel;
    private javax.swing.JButton question1;
    private javax.swing.JButton question10;
    private javax.swing.JButton question11;
    private javax.swing.JButton question12;
    private javax.swing.JButton question13;
    private javax.swing.JButton question14;
    private javax.swing.JButton question15;
    private javax.swing.JButton question16;
    private javax.swing.JButton question17;
    private javax.swing.JButton question18;
    private javax.swing.JButton question19;
    private javax.swing.JButton question2;
    private javax.swing.JButton question20;
    private javax.swing.JButton question3;
    private javax.swing.JButton question4;
    private javax.swing.JButton question5;
    private javax.swing.JButton question6;
    private javax.swing.JButton question7;
    private javax.swing.JButton question8;
    private javax.swing.JButton question9;
    private javax.swing.ButtonGroup questionButtonGroup;
    private javax.swing.JButton questionEndButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JPanel questionPanel1;
    private javax.swing.JPanel questionPanel2;
    private javax.swing.JRadioButton questionRadioButton1;
    private javax.swing.JRadioButton questionRadioButton2;
    private javax.swing.JRadioButton questionRadioButton3;
    private javax.swing.JDialog registration;
    private javax.swing.JLabel registrationBackground;
    private javax.swing.JButton registrationButton1;
    private javax.swing.JButton registrationButton2;
    private javax.swing.ButtonGroup registrationButtonGroup;
    private javax.swing.JLabel registrationLabel1;
    private javax.swing.JLabel registrationLabel2;
    private javax.swing.JLabel registrationLabel3;
    private javax.swing.JLabel registrationLabel4;
    private javax.swing.JLabel registrationLabel5;
    private javax.swing.JLabel registrationLabel6;
    private javax.swing.JLabel registrationLabel7;
    private javax.swing.JLabel registrationLabel8;
    private javax.swing.JMenuBar registrationMenuBar;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JRadioButton registrationRadioButton1;
    private javax.swing.JRadioButton registrationRadioButton2;
    private javax.swing.JTextField registrationTextField1;
    private javax.swing.JTextField registrationTextField2;
    private javax.swing.JTextField registrationTextField3;
    private javax.swing.JTextField registrationTextField4;
    private javax.swing.JTextField registrationTextField5;
    private javax.swing.JDialog result;
    private javax.swing.JLabel resultBackground;
    private javax.swing.JButton resultEndButton;
    private javax.swing.JLabel resultLabel1;
    private javax.swing.JLabel resultLabel2;
    private javax.swing.JLabel resultLabel3;
    private javax.swing.JMenuBar resultMenuBar;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton seeAnswerButton;
    private javax.swing.JLabel stidentTestLabel;
    private javax.swing.JButton studentStartTestButton;
    private javax.swing.JDialog studentTest;
    private javax.swing.JLabel studentTestBackground;
    private javax.swing.JMenuBar studentTestMenuBar;
    private javax.swing.JPanel studentTestPanel;
    private javax.swing.JDialog teacherTest;
    private javax.swing.JLabel teacherTestBackground;
    private javax.swing.JMenuBar teacherTestMenuBar;
    private javax.swing.JPanel teacherTestPanel;
    private javax.swing.JLabel testBackground;
    private javax.swing.JMenuBar testMenuBar;
    private javax.swing.JDialog testQuestion;
    // End of variables declaration//GEN-END:variables
}
